### ISSUE TITLE
Can't run objection on Windows 10: No module named '__main__.repl'

### ISSUE THREAD

**Issue by mydockergit** [sensepost/objection#202]
I installed `objection` by running: `pip3 install objection`.  
I opened `cmd.exe` and ran `objection` and it doesn't identify it.  

So I tried to run it manually by downloading the release and running `python C:\objection-1.5.2\objection\console\cli.py` and I received:  

> Traceback (most recent call last):
>   File "C:\Users\myuser\appdata\local\programs\python\python37-32\lib\site-packages\objection\console\cli.py", line 7, in <module>
>     from .repl import Repl
> ModuleNotFoundError: No module named '__main__.repl'; '__main__' is not a package

I am using Windows 10x64 and I have Python 3.7.  

How can I run it on Windows 10 ?

**Comment by mydockergit** [comment]
It works only if I run it from here:  
`C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\Scripts>objection`  

with cmd.exe (with PowerShell it doesn't work).  

Probably something related to the relative paths.

**Comment by PrinceGillji** [comment]
Same problem but not fixed

**Comment by aliaaaaaaa** [comment]
This  problem in most case happens if you have more than one python/scripts folder  on your system for example install more than one version of python on your system
solution:
go to your system settings  -> Advanced System Settings ->Environment variables -> system Variables -> Path -> and add/replace python scripts path with correct one for example
C:\Users\...\AppData\Local\Programs\Python\Python37-32\Scripts
