### ISSUE TITLE
Fail apk create

### ISSUE THREAD

**Issue by oldesec** [sensepost/objection#223]
Hello.

I am testing the emulator.

When I execute the command, the following error occurs.

Run command:
```
$ objection patchapk -s line.apk
No architecture specified. Determining it using `adb`...
Failed to determine architecture. Is the device connected and authorized?
```

**Comment by pahan12** [comment]
you need connect your android device over "usb debugging" before running this command

**Comment by aph3rson** [comment]
@oldesec, @pahan12 is exactly right - Objection uses ADB to determine the specific architecture for the new APK. If you don't have a device handy, but know the architecture, use the `-a` flag (e.g. `-a arm64`).

**Comment by praveen2gemini** [comment]
@ranjit-git  For me, I have connected adb and ensured adb shell commands are running successfully.
But still getting following error:
```
No architecture specified. Determining it using `adb`...
Failed to determine architecture. Is the device connected and authorized?
```

**Comment by z0xyz** [comment]
As for me, the problem turned out to be associated with adb visibility itself i.e., objection is incapable of finding adb, rather than finding the device architecture. If you were in the same boat as me and installed adb manually & locally somewhere else in your home directory, then symlinking it to the conventional `/usr/local/bin/` would work out. All in all, the exception is misleading.
