### ISSUE TITLE
iOS - Patched IPA Installation Error - The executable was signed with invalid entitlements.

### ISSUE THREAD

**Issue by Blueeyes3** [sensepost/objection#248]
Dear Team,

I am trying to patch an ipa file using objection for iOS pentest. However after using the code `'objection patchipa -s test.ipa --codesign-signature <code>'` the objection produces a patched ipa.

Now after unzipping the patched ipa and when running the command `'ios-deploy --bundle test.app -W -d'`, I am getting the below error.

```
[ 70%] VerifyingApplication
2019-07-09 14:58:27.287 ios-deploy[2097:92411] [ !! ] Error 0xe8008016: The executable was signed with invalid entitlements. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
```

Environment:
iOS version - 12.0
Device - iphone 8 (Non Jailbroken)
Frida Gadget version - 12.6.10

Note: This occurs only for one application. The same when I tried with another application it is working properly.

I made my research but still couldn't figure the workaround to do. Appreciate your help.

Thanks in Advance!

**Comment by leonjza** [comment]
Although I cannot give you a definitive answer, I suspect it may be because your target IPA has some entitlements that free developer accounts cannot have.

The only thing I can suggest is to try and do the signing process manually to debug (we use [node-applesign](https://github.com/nowsecure/node-applesign)) under the hood, implemented [here](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/ios.py#L406-L417).

Good luck!
