### ISSUE TITLE
command not found: objection [MacBook terminal]

### ISSUE THREAD

**Issue by poldenais** [sensepost/objection#291]
Description:
Im getting the command not found when attempting to run Objection. I can run Frida no problem and have python/pip installed.
objection --help                     

**To Reproduce**
Run command objection and its not found.

**Environment (please complete the following information):**

 - Frida 12.6.23

**Comment by blzhu** [comment]
I install "objection" success, and run the command "hash -r" , still can not use , "zsh: command not found: objection", macos catalina 10.15.6

**Comment by leonjza** [comment]
You will have to check your `$PATH`. Whatever your Python environment is, it's `bin/` directory needs to be in there somewhere.

**Comment by blzhu** [comment]
yes,I found objection and pip3 are in the same directory , /Library/Frameworks/Python.framework/Versions/3.7/bin/objection

**Comment by Nododo** [comment]
i also meet the same problem 

pip3 and python3 are in same path 

but still can't use objection

![WechatIMG3490](https://github.com/sensepost/objection/assets/10458305/96f2a2ec-a4b2-4c11-88f6-4a3bdb228e93)

**Comment by brandon-fryslie** [comment]
This is basic shell usage and not related to this app.  However for future readers, using `pipx` is highly recommended.

```shell
brew install pipx

# ensure $PATH includes directory for pipx executables (MacOS ONLY!  Linux users should already know how to do this)
echo $PATH | grep -q '/Users/.*/.local/bin' && echo 'path is set up correctly' || echo 'You need to add $HOME/.local/bin to your $PATH'

# run it directly
pipx run objection

# install it
pipx install objection

# ensure it's available
which objection
```

`pipx` creates an isolated venv for each python cli application, avoiding many potential issues and saving effort.  You won't have as many `$PATH` related issues using `pipx` since you will only need to add a single dir to your $PATH.  Otherwise, it's easy to install software into a python that isn't on your $PATH (systems typically have multiple python installations).
