### ISSUE TITLE
Exception in thread "main" org.jf.util.ExceptionWithContext

### ISSUE THREAD

**Issue by zafalija** [sensepost/objection#302]
**Describe the bug**
Objection cannot rebuild the apk after injecting frida, while I can easily decode and rebuild using apktool alone.
I'm using objection 1.8.2 and apktool 2.4.0 (not dirty)

**Evidence / Logs / Screenshots**
![Schermata da 2019-11-20 15-23-03](https://user-images.githubusercontent.com/56796741/69246915-dccca880-0ba9-11ea-981b-6a3329599f57.png)

**Comment by leonjza** [comment]
You can try out some of the flags in the `patchapk` command to see if any of them help. `objection patchapk --help` will tell you what is available. Otherwise, you would need to dig into the source code and debug from there.

The code section that wraps `apktool` to unpack can be found [here](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L345-L368), and to repackage [here](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L760-L783).
