### ISSUE TITLE
Support work profile/Android users

### ISSUE THREAD

**Issue by rugk** [sensepost/objection#396]
**Is your feature request related to a problem? Please describe.**
With Shelter or other apps, you can create a work profile.
Objection currently cannot detect apps installed in that profile.

With `adb shell pm list users` you can list them.

**Describe the solution you'd like**
A parameter like `--user` or so you can pass to inspect another user's app.

**Describe alternatives you've considered**
AFAIK this is not yet possible with the parameters we have.

**Additional context**
It's the same for multi-user Android systems or the work profile AFAIK, that is also "just" a user, basically.

Android 9

**Comment by leonjza** [comment]
Since Frida 12.11 I think this is totally possible yeah! `frida-tools` got [this commit](https://github.com/frida/frida-tools/commit/9c41977dd221f70d7ecf31d647ad9219104d5396) to pass on extra args, which also relates to the 12.11 release notes [here](https://frida.re/news/2020/07/24/frida-12-11-released/) mentioning the `uid` option for `spawn()`. I think we will need to use this to support this.

**Comment by Flangvik** [comment]
Facing this issue now , would be a solid feature to add!

**Comment by lauritzh** [comment]
I just stumbled over this use case, too. This would indeed be a great feature! :)

**Comment by CDuPlooy** [comment]
I added a `uid` option to the cli args, the changes can be seen in #525. I don't have an android for work profile setup, so if anyone could test I'd appreciate it :heart:

**Comment by lauritzh** [comment]
Hi @CDuPlooy,
thank you very much for your effort!
Unfortunately I do not have a test device at hand at the moment, either. 😢 

Maybe someone else here in this thread. 

Thanks again,
Lauritz
