### ISSUE TITLE
[bug] Objection crash

### ISSUE THREAD

**Issue by rypz79** [sensepost/objection#443]
**Describe the bug**
Objection crashes on the client-side (5.8.0-25-generic Linux on x64) when I hook a boolean method to always return TRUE while hooking an entire class from the app on the server-side (Magisk v22 on arm64-v8a) to dump args and return values

**To Reproduce**
[objection_CRASH.txt](https://github.com/sensepost/objection/files/6130344/objection_CRASH.txt)
to reproduce the crash UI wise after setting both hooks while ynet app is open 
1. goto (press on) ynet+ tab on the top left of the screen
2. select (press on) any story 

**Similar issues**
Not that I know of

**Expected behavior**
The story should open 

**Evidence / Logs / Screenshots**
Not needed see Objection_CRASH.txt lines 126-149

**Environment (please complete the following information):**
 - Device: Samsung Galaxy Note10+ (SM-N975F)
 - OS: Android 11
 - Frida Version:- Server: MagiskFrida 14.2.13-1, Client: 14.2.13
- Objection Version 1.10.1

**Application**
ynet v6.84
https://play.google.com/store/apps/details?id=com.goldtouch.ynet

**Additional context**
Most of the app's UI is in Hebrew.
If anything else is needed just let me know

Thank You

**Comment by leonjza** [comment]
I'm spread a bit thin at the moment and don't have an Android device readily available to test atm. I have a few suggestions. This is not an objection issue per-se. Theres a few things you can try.

- Try the new `android deoptimize` command before your hooks.
- Try a different Frida server version.
- Try and replicate the hooks in vanilla Frida, outside of objection. The boolean return logic is [here](https://github.com/sensepost/objection/blob/1.10.1/agent/src/android/hooking.ts#L351-L364). If you can replicate the crash, see what is causing it in Frida.
- Make sure the logic you are overriding the boolean value for doesn't rely on something else and is crashing because of that.
Good luck!

**Comment by rypz79** [comment]
SOLVED
android deoptimize
