### ISSUE TITLE
[bug] Bug Description Here

### ISSUE THREAD

**Issue by anylayer** [sensepost/objection#466]
- Please, fill in all of the sections in this template.
- Please read each section carefully. Each has a description of what information will help.
- Windows support is limited. There is a good chance that a pull request would help!
- The more information you give, the better.
- Remove this section when you are done.

**Describe the bug**
![image](https://user-images.githubusercontent.com/46556817/123932145-bd237600-d9c3-11eb-844a-cfd47e40d983.png)

**To Reproduce**
1. objection -N -h ip -p port -g com.android.target explore
2. memory search sign --string --offsets-only

**Similar issues**
Please link the issues in this repository that is similar to yours.
#326,#264

**Environment (please complete the following information):**
 - Device: [nexus 6P]
 - OS: [android 6.0]
 - Frida Version [12.11.18]
- Objection Version [ 1.8.4]

**Comment by IPMegladon** [comment]
This is a tricky one and I've found it is many times due to a race condition where the permissions on the memory changed while objection is using Memory.scan. 
Believe the error handling on this function is a bit better now though and it shouldn't crash the whole agent anymore, mostly mitigating the issue.
