### ISSUE TITLE
Change signature authority in objection.

### ISSUE THREAD

**Issue by venkata16sidhartha** [sensepost/objection#484]
Is there any way to change the signing authority in objection?

**Comment by IPMegladon** [comment]
Currently not automatically but you can manually replace the keystore here:
https://github.com/sensepost/objection/blob/master/objection/utils/assets/objection.jks
Here is the code used to access the keystore:
https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L942
That said, this issue is quite old so closing as stale for now.
