### ISSUE TITLE
是否可以增加同时删除多个job的功能

### ISSUE THREAD

**Issue by Hades-p** [sensepost/objection#708]
![image](https://github.com/user-attachments/assets/045e4cc0-1cde-4c3f-8347-e805601a0e60)

**Comment by IPMegladon** [comment]
It is not planned currently due to how the CLI and command completion works, but it might be a good candidate for a pull request. 
Do note that some of the job functionality does not work correctly currently, as even if you kill some jobs it will not unset the hooks. I have created a PR to fix that issue, which you can try if you use the jobs: https://github.com/sensepost/objection/pull/705
