### ISSUE TITLE
How to run Parallel  objection explore in multiple devie 

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#93]
Hi,

In case of two iOS devices 

How to specify that this command has to execute on device one and another command has to send on device two

i want to execute  one cmd on two device  at the same time

**Comment by leonjza** [comment]
Instrumenting two devices from within the same `explore` session is not currently supported and truthfully, I don't think that would be added anytime soon. However, since version 1.3.0 you may specify the target device to connect to with the `--serial` flag. Serials may be found by running the `frida-ls-devices` command.
